
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

#- name: Install MySQL
#  action: apt pkg=$item state=present
#  with_items:
#    - mysql-server-core-5.5
#    - mysql-client-core-5.5
#    - libmysqlclient-dev
#    - python-mysqldb
#    - mysql-server
#    - mysql-client

- name: install mysql server core
  apt:
    update_cache: yes
    name: mysql-server
    state: present

- name: install mysql client core
  apt:
    update_cache: yes
    name: python-mysqldb
    state: present

- name: install mysql lib mysqlclient-dev
  apt:
    update_cache: yes
    name: libmysqlclient-dev
    state: present

- name: install mysql pymysql db
  apt:
    update_cache: yes
    name: python-mysqldb
    state: present

- name: install mysql server
  apt:
    update_cache: yes
    name: mysql-server
    state: present


- name: Start the MySQL service
  action: service name=mysql state=started


- name: Sets the root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: 'pass'
    name: 'root'
    password: '123456'
    state: present


- name: Ensure anonymous users are not in the database
  mysql_user: user='' host=$item state=absent login_user="root" login_password="123456"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_user="root" login_password="123456"

