
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

#- name: Install MySQL
#  action: apt pkg=$item state=present
#  with_items:
#    - mysql-server-core-5.5
#    - mysql-client-core-5.5
#    - libmysqlclient-dev
#    - python-mysqldb
#    - mysql-server
#    - mysql-client
#
#- name: install mysql server core
#  apt:
#    update_cache: yes
#    name: mysql-server-core
#    state: present

- name: install mysql client core
  apt:
    update_cache: yes
    name: python-mysqldb
    state: present

- name: install mysql server core
  apt:
    update_cache: yes
    name: libmysqlclient-dev
    state: present

- name: install mysql pymysql db
  apt:
    update_cache: yes
    name: python-mysqldb
    state: present

- name: install mysql server
  apt:
    update_cache: yes
    name: mysql-server
    state: present

- name: install mysql client
  apt:
    update_cache: yes
    name: mysql-client
    state: present


- name: Start the MySQL service
  action: service name=mysql state=restarted

#- name: Remove the test database
#  mysql_db: name=test state=absent

#- name: Set MySQL root Password
#  mysql_user:
#    login_host: 'localhost'
#    login_user: 'root'
#    login_password: ''
#    name: 'root'
#    password: '123456'
#    state: present


#- name: Create deploy user for mysql
#  mysql_user: user="deploy" host="%" password=pass priv=*.*:ALL,GRANT
#
#- name: Ensure anonymous users are not in the database
#  mysql_user: user='' host=$item state=absent
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

#
#- name: Update mysql root password for all root accounts
#  mysql_user: name=root host={{item}} password={{mysql_root_password}}
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - localhost
#
