---
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: create new directory
  file:
    path: /tom
    state: directory

- name: create new directory
  file:
    path: /opt/tomcat
    state: directory


- name: Download Tomcat
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz
    dest: /opt/tomcat/
    remote_src: yes
    extra_opts: [--strip-components=1]


- name: Copy setenv.sh to /opt/tomcat/conf
  copy:
    src: /home/tusher/Desktop/javaPro/anplay/src/tomcatrole/files/setenv.sh
    dest: /opt/tomcat/conf
    owner: tomcat
    mode: '0777'

# original commands
#  Install tomcat
#  sudo apt update
#  cd /
#  mkdir tom
#  cd tom/
#  curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz
#  sudo tar xzvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
