---
- name: This is the tomcat installer
  hosts: webserver
  remote_user: tusher
  become: yes
  become_user: root
  tasks:
    - name: create new directory
      file:
        path: /tom
        state: directory





#
#  Install tomcat
#  sudo apt update
#  cd /
#  mkdir tom
#  cd tom/
#  curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz
#  sudo tar xzvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
